# Generated by Django 5.0.1 on 2024-04-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_name_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='profile_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='profile_name',
        ),
    ]
