# Generated by Django 5.0.1 on 2024-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_email_profile_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_add',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
