# Generated by Django 5.0.1 on 2024-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_add',
            field=models.EmailField(max_length=254),
        ),
    ]
