# Generated by Django 5.0.1 on 2024-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_display_name_alter_profile_email_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(db_column='username', max_length=63),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_add',
            field=models.EmailField(db_column='email', max_length=254),
        ),
    ]
