# Generated by Django 5.0.1 on 2024-04-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_display_name_alter_profile_email_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_add',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(default='default@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=63),
        ),
    ]
