# Generated by Django 5.0.1 on 2024-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_email_add_profile_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_add',
            field=models.EmailField(default='default@email.com', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
