# Generated by Django 5.0.1 on 2024-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_email_address_profile_email_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_add',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
