# Generated by Django 5.0.2 on 2024-05-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_article_author_article_header_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name']},
        ),
    ]
