# Generated by Django 5.0.2 on 2024-05-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images/wiki'),
        ),
    ]
