apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret-credentials
  namespace: django-app
  labels:
    app: postgres
  data:
    POSTGRES_DB: "django_app"
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "adminpw"