apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgtresdb-deployment
  template:
    metadata:
      labels:
        app: postgresdb-deployment
    spec:
      containers:
      - name: postgresdb-deployment
        image: 'postgres'
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: db-secret-credentials
        volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgres-pvc