apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgtresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
          name: db-secret-credentials
        volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: db-data