services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: mooky0/iscs30.23-project
    environment:
      - PORT=8000
    env_file:
      - web/.env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /hobbysite/migrate.sh && sh /hobbysite/migrate.sh && /hobbysite/entrypoint.sh"
  postgres_db:
    image: postgres
    command: -p 5432
    env_file:
      - web/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: