apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  default.cong:
    server{
    listen 80;
    server_name localhost;
    
    location /static/ {
      alias /static/;
    }
    
    location / {
      proxy_pass http://app-service:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      }
    }