apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx
        configMap:
        name: nginx-cm
      - name: staticfiles
        persistentVolumeClaim:
          claimName: staticfiles-pvc
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80