# Generated by Django 5.0.1 on 2024-03-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProuductType',
            new_name='ProductType',
        ),
    ]
