# Generated by Django 5.0.1 on 2024-04-26 06:31

import django.db.models.deletion
from django.db import migrations, models

from profiles.models import Profile


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0003_alter_product_type"),
        ("profiles", "0009_alter_profile_email_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=Profile.objects.get(display_name="gabadmin").id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="profiles.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Sale", "On Sale"),
                    ("Out of Stock", "Out of Stock"),
                ],
                default="Available",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("On Cart", "On Cart"),
                            ("To Pay", "To Pay"),
                            ("To Ship", "To Ship"),
                            ("To Receive", "To Receive"),
                            ("Delivered", "Delivered"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merchstore.product",
                    ),
                ),
            ],
        ),
    ]
