# Generated by Django 5.0.2 on 2024-05-07 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_comment_commission'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Full', 'Full'), ('Completed', 'Completed'), ('Discontinued', 'Discounted')], default='OPEN', max_length=12),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=255)),
                ('manpower_required', models.IntegerField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full')], default='Open', max_length=4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission')),
            ],
            options={
                'ordering': ['manpower_required'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplicant', to='user_management.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplication', to='commissions.job')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
