# Generated by Django 5.0.2 on 2024-05-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_remove_commission_people_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-status', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status', '-manpower_required', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-status', '-applied_on']},
        ),
    ]
